const { DataTypes } = require('sequelize')
const sequelize = require('../config/database')

module.exports = sequelize.define('IntimationDetail', {
  CLAIM_ID:              { type: DataTypes.STRING(255), primaryKey: true },
  CLAIM_TYPE:            { type: DataTypes.STRING(255) },
  INTIMATION_DATE:       { type: DataTypes.DATEONLY },
  DATE_OF_DEATH_EVENT:   { type: DataTypes.DATEONLY },
  DATE_OF_DEATH_REG:     { type: DataTypes.DATEONLY },
  DATE_OF_CREMATION:     { type: DataTypes.DATEONLY },
  DATE_OF_ACCIDENT:      { type: DataTypes.DATEONLY },
  TRANSACTION_STATUS:    { type: DataTypes.STRING(50) },
  POLICY_STATUS:         { type: DataTypes.STRING(255) },
  LIFE_ASR_STATUS:       { type: DataTypes.STRING(255) },
  SOURCE:                { type: DataTypes.STRING(50) },
  BOND_TYPE:             { type: DataTypes.STRING(100) },
  FIR_PM_RECEIVED:       { type: DataTypes.STRING(20) },
  DECLARED_BY_DOCTOR:    { type: DataTypes.STRING(5) },
  WHATSAPP_FLAG:         { type: DataTypes.STRING(5) },
  PLACE_OF_DEATH:        { type: DataTypes.STRING(100) },
  POLICY_STATUS_ON_DOD:  { type: DataTypes.STRING(50) },
  DEATH_CERTIFICATE:     { type: DataTypes.STRING(20) },
  DC_REG_NUMBER:         { type: DataTypes.STRING(100) },
  DC_REG_DATE:           { type: DataTypes.DATEONLY },
  DC_ISSUE_DISTRICT:     { type: DataTypes.STRING(100) },
  DC_ISSUING_AUTHORITY:  { type: DataTypes.STRING(200) },
  DC_TEHSIL:             { type: DataTypes.STRING(100) },
  DC_ISSUE_STATE:        { type: DataTypes.STRING(100) },
  DC_PLACE_ON_CERTIFICATE:{ type: DataTypes.STRING(200) },
  DC_VILLAGE_BLOCK:      { type: DataTypes.STRING(200) },
  DC_OFFICER_POSITION:   { type: DataTypes.STRING(200) },
  CAUSE_CODE:            { type: DataTypes.STRING(20) },
  CAUSE_DESCRIPTION:     { type: DataTypes.STRING(255) },
  CAUSE_CATEGORY:        { type: DataTypes.STRING(100) },
  CAUSE_SUB_TYPE:        { type: DataTypes.STRING(100) },
  CLAIM_REGISTRATION_TYPE:{ type: DataTypes.STRING(100) },
  CAUSE_IF_OTHERS:       { type: DataTypes.STRING(255) },
}, { tableName: 'intimation_details', timestamps: false, freezeTableName: true })
